### ISSUE TITLE
CMK 1.6, RobotMK 1.1.0 - Bakery does not work if piggyback host is set

### ISSUE THREAD

**Issue by kleinski** [simonmeggle/robotmk#141]
If Piggyback host is chosen and the hostname of the pb host is set, the bakery crashes

![image](https://user-images.githubusercontent.com/3239736/124502815-761ef180-ddc4-11eb-9c80-92e535caf07d.png)

`Traceback (most recent call last):
File "/omd/sites/omdprod/lib/python/cmk_base/cee/agent_bakery.py", line 364, in execute_bakery_plugin
bake_func(*func_args)
File "/omd/sites/omdprod/local/share/check_mk/agents/bakery/robotmk.py", line 39, in bake_robotmk
config = RMKConfigAdapter(myconf, opsys, execution_mode)
File "/omd/sites/omdprod/local/share/check_mk/agents/bakery/robotmk.py", line 183, in __init__
suitedict.update(suite_tuple[2].get('piggybackhost', {}))
ValueError: dictionary update sequence element #0 has length 1; 2 is required`

After changing line 183 to `suitedict.update({'piggybackhost':suite_tuple[2].get('piggybackhost', {})})` it works and the robotmk.yml has the corresponding entry:

![image](https://user-images.githubusercontent.com/3239736/124504008-eb8bc180-ddc6-11eb-9834-a0077be5428f.png)

But in the agent output the piggyback section is missing:
![image](https://user-images.githubusercontent.com/3239736/124504545-0579d400-ddc8-11eb-8203-7123681adfa4.png)

**Comment by kleinski** [comment]
Remark: I did set the `transmit_html` to `false` after I took the screen capture of the robotmk.yml.

**Comment by kleinski** [comment]
The bakery of 2.0 is not affected by this bug.
