### ISSUE TITLE
Log Level "Off" causes bakery crash

### ISSUE THREAD

**Issue by simonmeggle** [simonmeggle/robotmk#187]
If a suite is configured with log level "Off", the suite crashes: 

```
Error in bakery plugin "robotmk": 'log_level' Traceback (most recent call last): File "/omd/sites/cmm/lib/python/cmk_base/cee/agent_bakery.py", line 366, in execute_bakery_plugin bake_func(*func_args) File "/omd/sites/cmm/local/share/check_mk/agents/bakery/robotmk.py", line 56, in bake_robotmk config = RMK(myconf, opsys, execution_mode) File "/omd/sites/cmm/local/share/check_mk/agents/bakery/robotmk.py", line 228, in __init__ global_dict['log_level'] = conf['log_level'] KeyError: 'log_level' .
```

**Comment by simonmeggle** [comment]
Not reproduceable anymore.
