### ISSUE TITLE
Bakery crashes when RobotMK rule does not contain specific suites

### ISSUE THREAD

**Issue by simonmeggle** [simonmeggle/robotmk#45]
By default, suites can be omitted in the bakery rule; in this case, the plugin should simply execute _all_ robot tests in the `robotdir`. 
This does not work properly:

```
Traceback (most recent call last):
  File "/omd/sites/xxx/lib/python/cmk_base/cee/agent_bakery.py", line 364, in execute_bakery_plugin
    bake_func(*func_args)
  File "/omd/sites/xxx/local/share/check_mk/agents/bakery/robotmk", line 28, in bake_robotmk
    robot_test_suites = robot_global_conf.pop('suites')
KeyError: 'suites'
```

As a temporary solution, specify the suites which should be executed.

**Comment by simonmeggle** [comment]
#7a1857b2d51bdeef729072b4c1f52d91e62c0f27
